name: qt6-core24
summary: Qt6 runtime content snap based on Ubuntu core24
version: '6.4.2'
description: |
  This snap is to be consumed by various Qt applications using Qt 6. Precompiled libraries and binaries are staged from Ubuntu's official repository.

base: core24
grade: stable
confinement: strict
compression: lzo

platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]

slots:
  qt6-core24:
    interface: content
    read:
      - /

parts:
  qt6:
    plugin: nil
    stage-packages:
      # Platform dependencies
      - freeglut3-dev
      - libglib2.0-0
      - libglib2.0-bin
      - libglib2.0-0t64
      - libgdk-pixbuf2.0-0
      - libice6
      - libegl1
      - libgl1-mesa-dri
      - libglx-mesa0
      - libxkbcommon0
      - libpulse0
      - locales
      - locales-all
      - gettext
      - libdrm-dev
      - mesa-va-drivers
      - on amd64:
          - i965-va-driver
          - intel-media-va-driver

      # Qt desktop integration
      #- qtchooser
      - qt6-wayland
      - qdbus-qt6
      - qt6-gtk-platformtheme
      - qt6-xdgdesktopportal-platformtheme
      
      # Qt modules from core24
      - libqt6gui6t64
      - libqt6svg6
      - libqt6svgwidgets6
      - libqt6sql6-sqlite
      - libqt6waylandclient6
      - libqt6webenginewidgets6

      # other
      - gsettings-desktop-schemas
      - xdg-user-dirs
      - xkb-data # required for qt6-wayland

    prime:
      - -usr/share/doc/libdrm*
      - -usr/lib/*/cmake
      - -usr/lib/*/qt6/mkspecs
      - -usr/share/qt6/doc
      - -usr/share/ECM
      - -lib/udev
      - -usr/share/applications
      - -usr/share/apport
      - -usr/share/bug
      - -usr/share/icons
      - -usr/share/libwacom
      - -usr/share/lintian
      - -usr/share/pkgconfig

    override-prime: |
      set -eux
      craftctl default
      cd $CRAFT_PRIME
      find . -type f,l -name "*.h" -exec rm -f {} \;
